var Home_data = [
  {
    id: 0,
    image:"/image/s9.png",
    title: '芒果干',
    price: 0.01,
    stock: '有货',
    detail: '零食芒果片 休闲食品小吃',
    weight: "100g",
    service: '不支持退货',
    selected: true,
  },
  {
    id: 1,
    image: "/image/s8.png",
    title: '夏威夷果',
    price: 0.01,
    stock: '有货',
    detail: '零食坚果炒货',
    weight: "500g",
    service: '不支持退货',
    selected: true,
  },
  {
    id: 2,
    image: "/image/s7.png",
    title: '牛扎铁',
    price: 0.01,
    stock: '有货',
    detail: '网红零食',
    weight: "300g",
    service: '不支持退货',
    selected: true,
  },
  {
    id: 0,
    image: "/image/s9.png",
    title: '芒果干',
    price: 0.01,
    stock: '有货',
    detail: '零食芒果片 休闲食品小吃',
    weight: "100g",
    service: '不支持退货',
    selected: true,
  },
  {
    id: 1,
    image: "/image/s8.png",
    title: '夏威夷果',
    price: 0.01,
    stock: '有货',
    detail: '零食坚果炒货',
    weight: "半斤",
    service: '不支持退货',
    selected: true,
  },
  {
    id: 2,
    image: "/image/s7.png",
    title: '牛扎铁',
    price: 0.01,
    stock: '有货',
    detail: '网红零食',
    weight: "300g",
    service: '不支持退货',
    selected: true,
  },
  {
    id: 0,
    image: "/image/s9.png",
    title: '芒果干',
    price: 0.01,
    stock: '有货',
    detail: '零食芒果片 休闲食品小吃',
    weight: "100g",
    service: '不支持退货',
    selected: true,
  },
  {
    id: 1,
    image: "/image/s8.png",
    title: '夏威夷果',
    price: 0.01,
    stock: '有货',
    detail: '零食坚果炒货',
    weight: "半斤",
    service: '不支持退货',
    selected: true,
  },
  {
    id: 2,
    image: "/image/s7.png",
    title: '牛扎铁',
    price: 0.01,
    stock: '有货',
    detail: '网红零食',
    weight: "300g",
    service: '不支持退货',
    selected: true,
  }
]
module.exports = {
  homeIndex: Home_data
}